### ISSUE TITLE
Should theDOC- tests have live internal references

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/transitiontoepub#40]
Right now, the noteref and  glossary references have a target of ref="#" which means it does not go anywhere.

So, should the actionable items be valid references? The EPUB version would allow the  Reading System, probably Thorium to perform the action and the screen reader output could be tested?

If this is not the expetation, we should put a not in somewhere that the links are not valid.

Thoughts welcome.testing of this

**Comment by avneeshsingh** [comment]
The main objective of this test file is to check behaviour of AT with DPUB ARIA roles.

So, from this objective point of view, we do not need to put real references.

 

We can think of extending the objective, but whenever we do it we need to give time to it. This is because whenever we expand the scope, we end up including many many things in it.

**Comment by GeorgeKerscher** [comment]
We decided not to have live links. We put a statement explaining  this in the document.
